version: "3"

networks:
  loki:
    driver: overlay
  main_web:
    external: true

services:
  loki:
    image: grafana/loki:2.7.4
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    networks:
      - loki
    user: "0"
    volumes:
      - ./volumes/loki:/loki

  promtail:
    image: grafana/promtail:2.7.4
    volumes:
      - ./promtail-config.yaml:/etc/promtail/config.yml
      - /var/log:/var/log
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers
    networks:
      - loki

  grafana:
    image: grafana/grafana:9.2.2
    ports:
      - "3000:3000"
    user: "0"
    networks:
      - loki
      - main_web
    volumes:
      - ./volumes/grafana:/var/lib/grafana
      - ./datasources:/etc/grafana/provisioning/datasources/
#      - ./loki/grafana/provisioning/:/etc/grafana/provisioning/
    labels:
      - traefik.enable=true
      - traefik.port=3000
      - traefik.http.routers.gra.rule=Host(`gra.erkheikki.fi`)
      - traefik.http.routers.gra.tls=true
      - traefik.http.routers.gra.tls.certresolver=lets-encrypt
      - traefik.http.services.gra.loadbalancer.server.port=3000
